### ISSUE TITLE
Determine roadmap with regards to isparta/istanbul.

### ISSUE THREAD

**Issue by izaakschroeder** [adana-coverage/babel-plugin-transform-adana#20]
Pretty open to porting existing features from istanbul/isparta over. Obviously this project is nowhere near as mature, but maybe it's a good base to build new stuff on, especially with regards to instrumenting ES6 code. Pretty happy to have input here. Would be happy to have you guys on board! :smile: 

/cc @gotwarlost

**Comment by graingert** [comment]
istanbul babel support is now provided by babel-plugin-istanbul

**Comment by graingert** [comment]
@izaakschroeder ?

**Comment by izaakschroeder** [comment]
Oh. Well now that `istanbul` now has their own babel plugin they're pretty much all set 😄  That was the biggest drive for `adana` but there's still some cool features kicking around here I may keep playing with.
