### ISSUE TITLE
Error thrown on quoted object key

### ISSUE THREAD

**Issue by olegskl** [adana-coverage/babel-plugin-transform-adana#30]
Given the following .babelrc file:

``` json
{
  "presets": ["es2015"],
  "plugins": ["transform-adana"]
}
```

When there's an object declaration in a js file with a key surrounded by quotes:

``` js
export default {
  foo: 'bar', // this line is ok
  'baz': 'qux' // this line fails
};
```

Then Babel throws:

> TypeError: foo.js: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "SequenceExpression"
>     at validate (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-types/lib/definitions/index.js:101:13)
>     at Object.validate (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-types/lib/definitions/core.js:506:63)
>     at Object.validate (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-types/lib/index.js:269:9)
>     at NodePath._replaceWith (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-traverse/lib/path/replacement.js:201:7)
>     at NodePath.replaceWith (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-traverse/lib/path/replacement.js:179:8)
>     at instrument (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-plugin-transform-adana/dist/instrumenter.js:156:12)
>     at visitObjectProperty (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-plugin-transform-adana/dist/instrumenter.js:353:9)
>     at PluginPass.<anonymous> (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-plugin-transform-adana/dist/instrumenter.js:84:39)
>     at NodePath._call (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-traverse/lib/path/context.js:74:18)
>     at NodePath.call (/Users/olegsklyanchuk/repos/test/adana-test/node_modules/babel-traverse/lib/path/context.js:46:17)

**Comment by izaakschroeder** [comment]
Can't believe I didn't catch this originally… thanks for reporting! Bug has been fixed in #31 and released as part of `babel-plugin-transform-adana@0.5.4`.

:smile:
